CREATE TABLE STUDENT(
STUDENT_ID INT PRIMARY KEY NOT NULL,
STUDENT_NAME VARCHAR(30) NOT NULL,
STUDENT_MARKS INT NOT NULL
);
SELECT * FROM STUDENT;
INSERT INTO STUDENT VALUES(20091,"USHA",97);
INSERT INTO STUDENT VALUES(20092,"VYSHU",93);
INSERT INTO STUDENT VALUES(20093,"SAI",83);
INSERT INTO STUDENT VALUES(20094,"RANI",91);
INSERT INTO STUDENT VALUES(20095,"SAMEER",74);
INSERT INTO STUDENT VALUES(20096,"OMKAR",89);
INSERT INTO STUDENT VALUES(20097,"ANJUM",70);
INSERT INTO STUDENT VALUES(20098,"KAVYA",68);
INSERT INTO STUDENT VALUES(20099,"BHAVYA",75);
INSERT INTO STUDENT VALUES(20045,"POOJI",95);
INSERT INTO STUDENT VALUES(20067,"JITHU",82);

SELECT * FROM STUDENT WHERE STUDENT_MARKS = 74;

SELECT * FROM STUDENT WHERE STUDENT_MARKS < 74;

SELECT * FROM STUDENT WHERE STUDENT_MARKS <= 74;

SELECT * FROM STUDENT WHERE STUDENT_MARKS > 80;

SELECT * FROM STUDENT WHERE STUDENT_MARKS >= 83;

SELECT * FROM STUDENT WHERE STUDENT_ID >= 20092;

SELECT * FROM STUDENT WHERE STUDENT_MARKS != 91;

SELECT * FROM STUDENT WHERE STUDENT_MARKS <> 91;

SELECT * FROM STUDENT WHERE STUDENT_MARKS  BETWEEN 83 AND 99;

SELECT * FROM STUDENT WHERE STUDENT_MARKS BETWEEN 83 AND 99 ORDER BY STUDENT_MARKS;

-- ASCENDING ORDER BY USING KEY WORD ASC
SELECT * FROM STUDENT WHERE STUDENT_MARKS BETWEEN 83 AND 99 ORDER BY STUDENT_MARKS ASC;

-- DESENDING ORDER BY USING KEY WORD DESC
SELECT * FROM STUDENT WHERE STUDENT_MARKS BETWEEN 83 AND 99 ORDER BY STUDENT_MARKS DESC;


SELECT * FROM STUDENT WHERE NOT STUDENT_MARKS = 91;

SELECT * FROM rgm;

SELECT DISTINCT ADDRESS FROM rgm;

SELECT COUNT(DISTINCT ADDRESS) FROM rgm;

SELECT COUNT(DISTINCT STUDENT_MARKS) FROM STUDENT;

SELECT * FROM STUDENT ;

SELECT * FROM STUDENT WHERE NOT STUDENT_MARKS = 74 AND NOT STUDENT_MARKS = 91;

SELECT * FROM rgm LIMIT 3;

SELECT * FROM rgm WHERE ADDRESS = 'KURNOOL' LIMIT 2;

SELECT * FROM rgm WHERE ADDRESS = 'KURNOOL' LIMIT 2;

SELECT COUNT(ADDRESS),ADDRESS FROM rgm GROUP BY ADDRESS;

SELECT * FROM rgm;

SELECT * FROM rgm WHERE COLLEGE = 'RGMCET' ORDER BY ID LIMIT 5;

SELECT * FROM rgm WHERE COLLEGE = 'RGMCET' ORDER BY  ID DESC LIMIT 5;

CREATE TABLE DOB(
DATE_ DATE NOT NULL
);

INSERT INTO DOB VALUES ('2020-07-06');

SELECT * FROM DOB;



